
first_page_arrow_id <- "ctl00_mainContentPlaceHolder_liFirstPage"
next_page_arrow_id <- "ctl00_mainContentPlaceHolder_LinkButtonNextPage"
prev_arrow <- "ctl00_mainContentPlaceHolder_LinkButtonPreviousPage"
last_page_id <- "ctl00_mainContentPlaceHolder_liLastPage"
last_page_class <- "page-item disabled"
ul_pagination_class <- "pagination"
list_item_class <- "page-item"
anchor_nextpage_class <- "page-link"
anchor_nextpage_id <- "ctl00_mainContentPlaceHolder_LinkButtonNextPage"